### ISSUE TITLE
运行时出现这个

### ISSUE THREAD

**Issue by hejinding** [Samarium150/mirai-console-drift-bottle#23]
[92m2022-09-02 20:50:02 I/Drift Bottle: https://aip.baidubce.com/oauth/2.0/token?grant_type=client_credentials&client_id=&client_secret=[0m[m
[31m2022-09-02 20:50:02 E/Drift Bottle: 获取AccessToken失败[0m[m
[31m2022-09-02 20:50:02 E/Drift Bottle: kotlinx.serialization.MissingFieldException: Fields [refresh_token, expires_in, session_key, access_token, scope, session_secret] are required for type with serial name 'io.github.samarium150.baidu.aip.data.Credential', but they were missing
kotlinx.serialization.MissingFieldException: Fields [refresh_token, expires_in, session_key, access_token, scope, session_secret] are required for type with serial name 'io.github.samarium150.baidu.aip.data.Credential', but they were missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar//io.github.samarium150.baidu.aip.data.Credential.<init>(Credential.kt:21)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar//io.github.samarium150.baidu.aip.data.Credential$$serializer.deserialize(Credential.kt:21)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar//io.github.samarium150.baidu.aip.data.Credential$$serializer.deserialize(Credential.kt:21)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:55)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:147)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(ContentNegotiation.kt)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:173)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.client.HttpClient$4.invoke(HttpClient.kt)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.client.HttpClient$4.invoke(HttpClient.kt)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:91)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:138)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.client.call.HttpClientCall.body(HttpClientCall.kt:87)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar//io.github.samarium150.mirai.plugin.driftbottle.util.ContentCensor.getCredential(ContentCensor.kt:126)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar//io.github.samarium150.mirai.plugin.driftbottle.util.ContentCensor.access$getCredential(ContentCensor.kt:42)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar//io.github.samarium150.mirai.plugin.driftbottle.util.ContentCensor$getCredential$1.invokeSuspend(ContentCensor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at mirai-console-drift-bottle-1.11.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Samarium150** [comment]
提供一下你的`General.yml`和`ContentCensor.yml`

**Comment by Samarium150** [comment]
如果你在`General.yml`里开启了内容审核，则需要填写`ContentCensor.yml`中内容
